plugin:
  key: nozzlelifetracker
  name: Nozzle Life Tracker
  version: 0.2.7
  description: Tracks nozzle usage time and displays wear status.
  author: Andy Rabin
  license: AGPLv3
  homepage: https://github.com/Grexsnip/Octoprint_NozzleLifePlugin
  update:
    type: github_release
    user: Grexsnip
    repo: OctoPrint-NozzleLifeTracker
    current: 0.2.7
